# Generated by Django 5.1 on 2024-08-21 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My CV', max_length=100)),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=20)),
                ('urls', models.CharField(default='', max_length=255)),
                ('job', models.CharField(max_length=60)),
                ('about', models.CharField(default='', max_length=1500)),
                ('exp', models.CharField(max_length=1500)),
                ('edu', models.CharField(max_length=1500)),
                ('top_skills', models.CharField(max_length=255)),
                ('soft_skills', models.CharField(max_length=255)),
                ('lang', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
